config/routes.rb
Rails.application.routes.draw do

  get '/new', to:'posts#old'
  get '/threads', to: 'posts#threads'
  get '/thread/:id', to:'posts#thread'

  root 'posts#index'

  resources :posts, only: [:show] do
    collection do
      get "search", "search_js"
    end
    member do
      get "search_index"
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :update, :new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

  default_scope -> {order(oni_at: :asc)}
  
  has_many :likes, dependent: :destroy
  
  #validates :content, presence: true, length: {in: 10..22}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  ##ここでincludeすることで、SessionHelper moduleが全てのコントローラーに適応される。
  
private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインが必要です"
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'nkf'
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 50)
  end
  
  
  def show
    @post = Post.find(params[:id])
  end
  
  def thread
    @title = params[:id]
    @posts = Post.where(title: params[:id]).paginate(page: params[:page], per_page: 50)
  end
  
  def threads
  end
  
  def create
    @post = current_user.posts.build(post_params)
    @post.content = NKF.nkf("-Xw",@post.content)#大文字に変換
    if @post.save
      flash[:success] = "投稿に成功しました！"
      redirect_to post_path(@post)
    else
      flash.now[:danger] = "エラーが発生しました。"
      render 'home'
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "削除に成功しました！"
    redirect_to current_user
  end
  
  def search
    if search_params[:keyword].blank?##空で検索した場合
      redirect_to posts_path
    else
      redirect_to search_index_post_path(search_params[:keyword])
    end
  end
  
  def search_js
    @posts2 = Post.where('content LIKE(?)', "%#{search_params[:keyword]}%").or(Post.where('oni_content LIKE(?)', "%#{search_params[:keyword]}%")).order('content ASC').limit(6)
  end
  
  def search_index
    @posts1 = Post.where('content LIKE(?)', "%#{params[:id]}%").or(Post.where('oni_content LIKE(?)', "%#{search_params[:keyword]}%")).order('content ASC').limit(10).paginate(page: params[:page])
  end
  
private

  def post_params
    params.require(:post).permit(:content)
  end
  
  def search_params
    params.permit(:keyword)
  end
  
  
  def please_log_in
    unless logged_in?
      flash.now[:danger] = "投稿するためには登録が必要です。"
      render 'home'
    end
  end
  
  def correct_user
    @post = current_user.posts.find(params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])#formの内容が正しい場合
      if user.activated?#メールで有効かしているか否か
        remember(user)
        log_in(user)
        
        if params[:session][:remember_me] == 1
          remember(user)
        else
          forget(user)
        end
        
        redirect_back_or user
        flash[:sucess] = "ログインに成功しました！"
      else#有効化していない場合
        flash[:warning] = "アカウント認証のメールをご確認ください。"
        redirect_to root_url
      end
    else
      flash.now[:danger] = "メールアドレスかパスワードが正しくありません"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
private
  
  def email_params
    params.require(:session).permit(:email)
  end
  
  def password_params
    params.require(:session).permit(:password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '俳句で繋がる')
        base_title = "俳句で繋がる"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def half_to_full(str)
    str.tr('0-9a-zA-Z', '０-９ａ-ｚＡ-Ｚ')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    #user_idに現在のユーザーのidを代入。
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(session[:user_id])
    elsif (user_id = cookies[:user_id])
      user = User.find(user_id)
      if user && user.authenticated?(:remember,cookies[:remember_token])
        log_in(user)#sessionをセット
        @current_user = user
      end
    end
  end
 
  def logged_in?
    !current_user.nil?
  end
  
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav-head">
    <%= link_to root_path do %>
      <%= image_tag("oni.png", size: '80x80',class: "logo") %><span class="header-title">鬼の説法</span>
    <% end %>
    
      <ul class="nav navbar-nav navbar-right">

        <li class ="search">
          <div id="search-box">
            <%= form_tag(search_posts_path, method: :get, id: "form2",
            :data => {:toggle=>"popover", :content => "", :trigger => "focus"},) do %>
              <%= text_field_tag :search, "", id: "form1", class: "search__query", 
              name: "keyword", placeholder: "キーワードで検索",autocomplete: "off" %>
              <div id="search_result"></div>
              <%= button_tag '検索', class: 'btn-gradient-3d-orange search-btn' %>
            <% end %>
          </div>
        </li>
        
        <li class="home-use">
          <%= link_to "鬼和尚について" %>
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            並び替え <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "鬼和尚の単発投稿" %></li>
            <li><%= link_to "スレッドを選ぶ" %></li>
            <li>
              <%= link_to "a" %>
            </li>
          
          <li class="sign-up">
            <%= link_to "新規登録" %>
          </li>
          

      </ul>
    </nav>
  </div>
</header>


<style>
  .logo3 {
    margin-left: 20px;
    
  }
  .logo{
    border-radius: 50%;
  }
</style>

<style>

.ui-autocomplete {
    max-height: 100px;
    overflow-y: auto;
    overflow-x: hidden;
    padding-right: 20px;
}
#jquery-ui-autocomplete label {
    float: left;
    margin-right: 0.5em;
    color: black;
    font-size: 15px;
}

</style>

<script>
  /* global $ */
$(document).ready(function(){
  var
  preFunc = null,
  preInput = '',
  input = '',
  ajaxSearch = function(input) {
    $.ajax({
      url: "/posts/search_js",
      type: "GET",
      data: ("keyword=" + input)
    });
  };
  $('#form1').on('keyup', function() {
    input = $.trim($(this).val());
    if(preInput !== input){
      clearTimeout(preFunc);
      preFunc = setTimeout(ajaxSearch(input), 500);
    }
    
    var result = $("#search_result").html();
      $("#form2").popover({
        content: $("#search_result"),
        placement: "bottom",
        html: true,
        trigger: "focus"
      });
      
    if(input == ""){
      $("#form2").popover("hide");
    }else{
      $("#form2").popover("show");
    }
    preInput = input;
  });
});
</script>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
     <title><%= full_title(yield(:title)) %></title>
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
　　<%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container container2">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

<script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
</script>

app/views/password_resets/edit.html.erb
<% provide(:title, 'パスワードの再設定') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "新しいパスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "新しいパスワードの確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワードの再設定") %>
<h1>パスワードの再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "メールを送信", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<li class="o-post">

  
    <% time = post.created_at %>
    <% content = post.content %>
    <% if not content == nil %>
    
    
     <div class="box25">
        <% if not time == nil %>
          <span class="box-title2"><%= post.number %>    <%= post.name %>   【<%= time.strftime("%Y-%m-%d") %>】</span>
        <% else %>
          <span class="box-title2"><%= post.number %>    <%= post.name %>   【<%= time %>】</span>
        <% end %>
        <p><%= simple_format(content) %></p>
     </div>
     
     <div class="box26">
       <span class="box-title">鬼和尚 【<%= post.oni_at.strftime("%Y-%m-%d") %>】</span>
       <p><%= simple_format(post.oni_content.gsub(" ","")) %></p>
     </div>
     
     
     <% else %>
     
     <div class="box26">
       <span class="box-title"><%= post.number %> 鬼和尚 【<%= post.oni_at.strftime("%Y-%m-%d") %>】</span>
       <p><%= simple_format(post.oni_content.gsub(" ","")) %></p>
     </div>
     
     <% end %>



</li>


<style>
.o-post{
  margin-top:70px;
}
  .box26 {
    position: relative;
    margin: 2em 0;
    padding: 0.5em 1em;
    border: solid 3px #FF6699;
    border-radius: 8px;
}
.box26 .box-title {
    position: absolute;
    display: inline-block;
    top: -13px;
    left: 10px;
    padding: 0 9px;
    line-height: 1;
    font-size: 19px;
    background: #FFF;
    color: #FF6699;
    font-weight: bold;
    font-family: serif;
}
.box26 p {
    margin: 0; 
    padding: 0;
    font-family: serif;
}
  .box25 {
    position: relative;
    margin: 2em 0;
    padding: 0.5em 1em;
    border: solid 3px #95ccff;
    border-radius: 8px;
}
.box25 .box-title2 {
    position: absolute;
    display: inline-block;
    top: -13px;
    left: 10px;
    padding: 0 9px;
    line-height: 1;
    font-size: 19px;
    background: #FFF;
    color: #95ccff;
    font-weight: bold;
    font-family: serif;
}
.box25 p {
    margin: 0; 
    padding: 0;
    font-family: serif;
}
.logo{
    border-radius: 50%;
    margin-bottom: 10px;
  }
</style>

app/views/posts/index.html.erb
<% provide(:title, '新しい順') %>

<%= will_paginate %>
<ul class="posts">
  <%= render @posts %>
</ul>
<%= will_paginate %>

app/views/posts/old.html.erb
<% provide(:title, '古い順') %>

<%= will_paginate %>
<ul class="posts">
  <%= render @posts %>
</ul>
<%= will_paginate %>

app/views/posts/search_index.html.erb
<% provide(:title, '検索結果') %>
<h1>検索結果</h1>
<%= will_paginate @posts1 %>
<ul class="posts">
  <%= render :partial => 'post', :collection => @posts1 %>
</ul>
<%= will_paginate @posts1 %>

app/views/posts/search_js.js.erb
<% if false %>
<% flash[:success] = "表示に成功" %>
<% @posts2 = Post.where('content LIKE(?)', "%#{search_params[:keyword]}%").order('content ASC').limit(10) %>
<% end %>
$("#search_result").html("<%= escape_javascript(render :partial =>"shared/search",:collection => @posts2, :as => "post2") %>");

app/views/posts/show.html.erb
<li class="o-post">

  
    <% time = @post.created_at %>
    <% content = @post.content %>
    <% if not content == nil %>
    
    
     <div class="box25">
        <% if not time == nil %>
          <span class="box-title2"><%= @post.number %>    <%= @post.name %>   【<%= time.strftime("%Y-%m-%d") %>】</span>
        <% else %>
          <span class="box-title2"><%= @post.number %>    <%= @post.name %>   【<%= time %>】</span>
        <% end %>
        <p><%= simple_format(content) %></p>
     </div>
     
     <div class="box26">
       <span class="box-title">鬼和尚 【<%= @post.oni_at.strftime("%Y-%m-%d") %>】</span>
       <p><%= simple_format(@post.oni_content.gsub(" ","")) %></p>
     </div>
     
     
     <% else %>
     
     <div class="box26">
       <span class="box-title"><%= @post.number %> 鬼和尚 【<%= @post.oni_at.strftime("%Y-%m-%d") %>】</span>
       <p><%= simple_format(@post.oni_content.gsub(" ","")) %></p>
     </div>
     
     <% end %>



</li>


<style>
.o-post{
  margin-top:70px;
}
  .box26 {
    position: relative;
    margin: 2em 0;
    padding: 0.5em 1em;
    border: solid 3px #FF6699;
    border-radius: 8px;
}
.box26 .box-title {
    position: absolute;
    display: inline-block;
    top: -13px;
    left: 10px;
    padding: 0 9px;
    line-height: 1;
    font-size: 19px;
    background: #FFF;
    color: #FF6699;
    font-weight: bold;
    font-family: serif;
}
.box26 p {
    margin: 0; 
    padding: 0;
    font-family: serif;
}
  .box25 {
    position: relative;
    margin: 2em 0;
    padding: 0.5em 1em;
    border: solid 3px #95ccff;
    border-radius: 8px;
}
.box25 .box-title2 {
    position: absolute;
    display: inline-block;
    top: -13px;
    left: 10px;
    padding: 0 9px;
    line-height: 1;
    font-size: 19px;
    background: #FFF;
    color: #95ccff;
    font-weight: bold;
    font-family: serif;
}
.box25 p {
    margin: 0; 
    padding: 0;
    font-family: serif;
}
.logo{
    border-radius: 50%;
    margin-bottom: 10px;
  }
</style>

app/views/posts/thread.html.erb
<% provide(:title, @title) %>

<h2 class="title"><%= @title %></h2>
<%= will_paginate %>
<ul class="posts">
  <%= render @posts %>
</ul>
<%= will_paginate %>

<style>
    h2.title{
        margin-top: 120px;
        font-size: 19px;
        background: #FFF;
        color: #FF6699;
        font-weight: bold;
        font-family: serif;
    }

</style>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count%>個のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/shared/_search.html.erb
<div id="windows">
 <p><%= link_to post2.content, post_path(post2) , class: "window"%></p>                 
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>準備中</h1>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "プロフィールを編集") %>

<div class="submit-form">
  <div class="left">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <div class="profile-image">
        <% if not @user.image? %>
          <%= image_tag("default.png", size: '160x160', class: "radius") %>
        <% else %>
          <%= image_tag(@user.image, size: "160x160", class: "radius") %>
        <% end %>
        <%= f.file_field :image , class: "change-image"%>
      </div>
      
      <div class="cp_iptxt">
      	<%= f.text_field :name, placeholder: "お名前" %>
      	<i class="fa fa-user fa-lg fa-fw" aria-hidden="true"></i>
      </div>
      <div class="cp_iptxt">
      	<%= f.email_field :email,  placeholder: "E-Mail" %>
      	<i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
      </div>

      <%= f.submit "変更を保存", class: "btn-gradient-3d  sub-bt" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザーの一覧') %>
<h1>ユーザーの一覧</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, '登録') %>

<div class="submit-form">
  <div class="left">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  
    <div class="cp_iptxt">
    	<%= f.text_field :name, placeholder: "お名前(10文字以下)" %>
    	<i class="fa fa-user fa-lg fa-fw" aria-hidden="true"></i>
    </div>
    
    
    <div class="cp_iptxt">
    	<%= f.email_field :email,  placeholder: "E-Mail" %>
    	<i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
    </div>
    
    <div class="cp_iptxt">
    	<%= f.password_field :password,  placeholder: "パスワード(6文字以上)" %>
    	<i class="fas fa-key fa-lg fa-fw" aria-hidden="true"></i>
    </div>
    <div class="cp_iptxt">
    	<%= f.password_field :password_confirmation,  placeholder: "パスワードの確認" %>
    	<i class="fas fa-key fa-lg fa-fw" aria-hidden="true"></i>
    </div>
    <%= f.submit "登録", class: "btn-gradient-3d sub-bt" %>
  <% end %>
  </div>
</div>
      



<style>


</style>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% if not @user.image? %>
          <%= image_tag("default.png", size: '160x160', class: "radius") %>
        <% else %>
          <%= image_tag(@user.image.url, size: "160x160",class: "radius") %>
        <% end %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>俳句一覧 (<%= @user.posts.count %>)</h3>
      <ul class="posts">
        <%= render @posts %>
      </ul>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>

<% if current_user && current_user.admin? && current_user == @user %>
  <%= link_to "削除", user_path(@user), method: :delete, data: {confirm: "本当に削除しますか？"} %>
<% end %>